package com.example.bmne.dao.bean;

import lombok.Builder;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table wk_content_log
 */
@Builder
public class WkContentLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_content_log.id
     *
     * @mbg.generated Thu Sep 28 15:12:06 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_content_log.content
     *
     * @mbg.generated Thu Sep 28 15:12:06 CST 2023
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_content_log.create_time
     *
     * @mbg.generated Thu Sep 28 15:12:06 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_content_log.creator
     *
     * @mbg.generated Thu Sep 28 15:12:06 CST 2023
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wk_content_log.status
     *
     * @mbg.generated Thu Sep 28 15:12:06 CST 2023
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_content_log.id
     *
     * @return the value of wk_content_log.id
     *
     * @mbg.generated Thu Sep 28 15:12:06 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_content_log.id
     *
     * @param id the value for wk_content_log.id
     *
     * @mbg.generated Thu Sep 28 15:12:06 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_content_log.content
     *
     * @return the value of wk_content_log.content
     *
     * @mbg.generated Thu Sep 28 15:12:06 CST 2023
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_content_log.content
     *
     * @param content the value for wk_content_log.content
     *
     * @mbg.generated Thu Sep 28 15:12:06 CST 2023
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_content_log.create_time
     *
     * @return the value of wk_content_log.create_time
     *
     * @mbg.generated Thu Sep 28 15:12:06 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_content_log.create_time
     *
     * @param createTime the value for wk_content_log.create_time
     *
     * @mbg.generated Thu Sep 28 15:12:06 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_content_log.creator
     *
     * @return the value of wk_content_log.creator
     *
     * @mbg.generated Thu Sep 28 15:12:06 CST 2023
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_content_log.creator
     *
     * @param creator the value for wk_content_log.creator
     *
     * @mbg.generated Thu Sep 28 15:12:06 CST 2023
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wk_content_log.status
     *
     * @return the value of wk_content_log.status
     *
     * @mbg.generated Thu Sep 28 15:12:06 CST 2023
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wk_content_log.status
     *
     * @param status the value for wk_content_log.status
     *
     * @mbg.generated Thu Sep 28 15:12:06 CST 2023
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}