#配置连接数据库
spring:
  datasource:
    username: root
    password: Love2023@
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://116.196.96.64:3306/wk-db
    type: com.alibaba.druid.pool.DruidDataSource

#配置mybatis-plus
mybatis-plus:
  configuration:
    #日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰形式显示
    map-underscore-to-camel-case: true
  #扫描mapper.xml文件
  mapper-locations: classpath:mapper/*.xml


