package com.example.bmne.dao.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.example.bmne.dao.bean.WkContentLog;
import org.apache.ibatis.annotations.Mapper;


import java.util.List;
@Mapper
public interface WkContentLogMapper extends BaseMapper<WkContentLog> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_content_log
     *
     * @mbg.generated Thu Sep 28 15:12:06 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_content_log
     *
     * @mbg.generated Thu Sep 28 15:12:06 CST 2023
     */
    int insert(WkContentLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_content_log
     *
     * @mbg.generated Thu Sep 28 15:12:06 CST 2023
     */
    WkContentLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_content_log
     *
     * @mbg.generated Thu Sep 28 15:12:06 CST 2023
     */
    List<WkContentLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wk_content_log
     *
     * @mbg.generated Thu Sep 28 15:12:06 CST 2023
     */
    int updateByPrimaryKey(WkContentLog record);
}